{{initialize_pkmn}}

<body>
    {{navbar}}
    
    {{sidebarOpen}}
                        <h1 align="center"><big>Alakazam</big></h1>
                        <img style="width:50%; margin:5px; float:right;" align="top" src="{[path]}images/Alakazam.png">
                        <h2>Info sul Pokémon:</h2>

{{table_stat|55|50|45|135|95|120|color=F99CB8|bordercolor=F85888}}

    {{sidebarClose}}
    
    {{footer}}
</body>
</html>