{{initialize_pkmn}}

<body>
    {{navbar}}
    
    {{sidebarOpen}}
                        <h1 align="center"><big>Alakazam</big></h1>
                        <img class="hidden-xs" style="width:50%; margin:5px; float:right;" align="top" src="{[path]}images/Alakazam.png">
                        <h2>Info sul Pokémon:</h2>
						

    {{table_stat|55|50|45|135|95|120|color=F99CB8|bordercolor=F85888}}
						<br>
						<div style="font-size:120%">
						<p> Alakazam è un attaccante speciale veloce di tipo Psico con 135 di SpA e 120 di Vel, classificato come OU.<br> </p>
						<h3>	<big>Proposta principale:</big> <br> </h3>
						<p>
							Alakazam @ assorbisfera <br>
							Abilità: Magiscudo <br>
							PA: 4 Dif / 252 SpA / 252 Vel <br>
							Natura timida <br>
							- Psichico <br>
							- Focalcolpo <br>
							- Palla ombra <br>
							- Introforza (ghiaccio)/Provocazione/Sostituto <br>
						</p>
						<p>Psichico è preferito a Psicoshock per la maggior potenza base e per poter colpire alcuni attaccanti fisici come Conkeldurr e Garchomp.
						Focalcolpo permette di colpire i Pokémon di tipo Buio, immuni a Psichico, e i Pokémon accaio. Palla ombra consente di uccidere altri Pokémon Psico ed eliminare in un 
						colpo solo gli Spettro che sono un problema per Alakazam. Introforza Ghiaccio è utile per abbattere alcuni Pokémon come Gliscor o Landorus in un colpo solo. Provocazione serve
						contro alcuni Pokémon basati su mosse di Stato che non eludiamo grazie a Magiscudo. Sostituto può essere usato sui cambi avversari per fornire due turni "sicuri" ad Alakazam. L'assorbisfera
						aumenta del 30% i danni, permettendo di uccidere un gran numero di attaccanti nemici in un colpo solo.<br>
						In questo set Alakazam occupa il ruolo di ripulitore del team avversario, che nelle fasi finali della partita non riesce a fermarlo.
						Può essere usato in combo con Retromarcia o Invertivolt per facilitare il suo ingresso in campo. Grazie alla sua abilità non teme i danni indiretti, cosa che rende molto difficile fermarlo e gli consente di 
						entrare su molti Pokémon che usano mosse di Stato.</p>
						<br><h3>	<big>Seconda proposta:</big> <br> </h3> <br>
						<p>
						
						Alakazam @ focalnastro <br>
						Abilità: Magiscudo<br>
						PA: 4 Dif / 252 SpA / 252 Vel<br>
						Natura timida<br>
						- Psichico<br>
						- Focalcolpo<br>
						- Introforza (Ghiaccio)/Palla ombra<br>
						- Tuononda<br>
						</p>
						<p>In questa variante Alakazam rinuncia all'assorbisfera ma ottiene un turno aggiuntivo grazie a focalnastro e alla sua abilità.
						Tuononda permette di rallentare gli attaccanti avversari e renderli facili bersagli. A causa dei danni inferiori Alakazam non copre più il ruolo di ripulitore e grazie alla possibilità di avere un secondo
						turno con focalnastro può entrare su molti nemici anche nelle prime fasi della partita.
						</p>
						<br><h3>	<big>Counter:</big> <br> </h3> <br>
						<p> Alakazam deve evitare alcuni Pokémon come Mandibuzz che non riesce ad eliminare in un colpo solo e che possono ucciderlo con Sbigoattacco.
						Deve anche evitare Scizor e Tyranitar che con Inseguimento possono intrapporarlo e ucciderlo in seguito. Anche alcune mosse ad alta priorità
						come Pugnoscarica o Geloscheggia possono essere un problema e non bisogna dimenticare la stolascelta che consente a molti Pokémon di superare in velocità Alakazam.</p>
						</div>
    {{sidebarClose}}
    
    {{footer}}
</body>
</html>