{{initialize_pkmn}}

<body>
    {{navbar}}
    
    {{sidebarOpen}}
                        <h1 align="center"><big>Dragonite</big></h1>
                        <img class="hidden-xs" style="width:50%; margin:5px; float:right;" align="top" src="{[path]}images/Dragonite.png">
                        <h2>Info sul Pokémon:</h2>

{{table_stat|91|134|95|100|100|80|color=9F77FF|bordercolor=CEBFFB}}
					<div style="font-size:120%"> <br>
						<p>Dragonite è un attaccante fisico con buone capacità difensive e ottime mosse a disposizione come Dragodanza, classificato OU.
						L'abilità Multisquame dimezza i danni subiti se si è a pieni PS rendendo quasi impossibile uccidere Dragonite in un colpo solo. </p>
						<br> 
						<h3><big>Proposta principale:</big> <br> </h3>
						<p>
						Dragonite @ Baccaprugna <br>
						Abilità: Multisquame <br>
						PA: 4 PS / 252 Att / 252 Spe<br>
						Natura Adamantina <br>
						- Dragodanza <br>
						- Oltraggio/Dragartigli <br>
						- Extrarapido/Fuocopugno/Trespolo <br>
						- Terremoto <br>
						</p> 
						<p>
						La mossa principale di questo set è Dragodanza che consente a Dragonite di superare in velocità quasi tutti gli attaccanti veloci e inoltre 
						aumenta i suoi danni. Si può sostituire Dragartigli con Oltraggio se si vuole più potenza. Extrarapido con +2 di priorità permette di colpire Pokémon
						come Talonflame o Weavile. Fuocopugno elimina in un solo colpo Pokémon come Skarmory, Ferrothorn e Magnezone che possono fermare Dragonite. Trespolo è utile per recuperare PS e ripristinare Multisquame.
						Terremoto è utile per uccidere i Pokémon di tipo Accaio che resistono a Dragartigli. La Baccaprugna toglie tutte le condizioni di stato che possono danneggiare gravemente Dragonite ed entra in combo con Oltraggio per rimuovere la confusione.
						Con questo set Dragonite si propone come un ripulitore in grado di entrare su molti Pokémon e alzare le proprie statistiche ma estremamente vulnerabile una volta persa Multisquame.
						Per essere veramente efficacie deve essere giocato dopo l'eliminazione dei suoi counter e poter usare una o due Dragodanze.  
						</p>
						<br><h3>	<big>Seconda proposta:</big> <br> </h3> 
						<p>
						Dragonite @ Bendascelta<br>
						Abilità: Multisquame<br>
						PA:  4 PS / 252 Att / 252 Spe<br>
						Natura Adamantina<br>
						- Oltraggio/Dragartigli<br>
						- Extrarapido/Fuocopugno<br>
						- Fuocopugno/Tuonopugno<br>
						- Terremoto<br>
						</p>
						<p>
						In questa variante Dragonite si propone come un attaccante fisico lento con danni incredibili fin dal primo turno. Grazie alla bendascelta ottiene un grandissimo potere offensivo, ma deve rinunciare 
						a Dragodanza. Rinuncia al suo ruolo di ripulitore, ma può essere riutilizzato anche senza Multisquame non dovendo spendere il primo turno per aumentare le proprie statistiche. 
						Tuonopugno è ottimo contro Azumarill e Togekiss.  
						</p>
						<br><h3><big>Terza proposta:</big> <br> </h3> 
						<p>
						Dragonite @ Avanzi<br>
						Abilità: Multisquame<br>
						PA: 216 PS / 64 Att / 228 SpD<br>
						Natura Adamantina<br>
						- Trespolo<br>
						- Dragartigli<br>
						- Extrarapido/Terremoto<br>
						- Fuocopugno/Terremoto<br>
						</p>
						<p>
						Con questo set Dragonite appare come un attaccante con alto potenziale difensivo. La sua abilità combinata con avanzi e trespolo lo rendono molto difficile da eliminare 
						per altri attaccanti (ma lo lasciano vulnerabile alle condizioni d stato). Le sue alte statistiche offensive gli permettono di infliggere molti danni e sconfiggere la maggior parte 
						degli attaccanti avversari. Dragartigli è preferito a Oltraggio per evitare di rimanere bloccato diversi turni.
						</p>
						<br><h3><big>Counter:</big> <br> </h3> 
						<p> Il più grande problema di Dragonite sono le mosse Ghiaccio in grado di sconfiggerlo facilmente. Levitoroccia annulla la sua abilità rendendolo estremamente
						vulnerabile. Le condizioni di stato danneggiano enormemente Dragonite che non ha un modo per evitarle. I Pokémon di tipo Folletto sono un problema in quanto immuni alle sue mosse Drago.
						Anche la stolascelta e le mosse ad alta priorità sono da evitare soprattutto quando Multisquame non è più attiva.</p>
					</div>	 
						
    {{sidebarClose}}
    
    {{footer}}    
</body>
</html>