{{initialize_pkmn}}

<body>
    {{navbar}}
    
    {{sidebarOpen}}
                        <h1 align="center"><big>Dragonite</big></h1>
                        <img style="width:50%; margin:5px; float:right;" align="top" src="{[path]}images/Dragonite.png">
                        <h2>Info sul Pokémon:</h2>

{{table_stat|91|134|95|100|100|80|color=9F77FF|bordercolor=CEBFFB}}

    {{sidebarClose}}
    
    {{footer}}    
</body>
</html>