{{initialize_dex}}
 
<body>    
    {{navbar}}
    
    {{sidebarOpen}}
                        <h2 align="left">Editor:</h2>
                        <textarea name="pageCode" cols="40" rows="5" id="pageCode" style="width:95%; height:100%;"></textarea>
                        <button type="submit" class="btn btn-default" id="save" value="Save">Save</button>
	{{sidebarClose}}
    
    {{footer}}
	<!-- FileSaver.js -->
	<script src="../script/FileSaver.js"></script>
	<!-- Scripts for editing -->
	<script src="../script/editor.js"></script>
    
    </body>
</html>